### ISSUE TITLE
Progress bar and another

### ISSUE THREAD

**Issue by BuilderGaming** [iKlem/GoulpLoader#3]
Hello,

The progress bar does not seem to work and I want "terrortown" (The name of the folder) renamed to "Trouble in Terrorist Town" can you do that? :)

**Comment by iKlem** [comment]
For the renamming of the Game mode, that can be with an update. 
For the progress bar, it's very strange the way it works. I'll try something for the next update.
Thanks for the feedback :+1:

**Comment by BuilderGaming** [comment]
Thanks man. :+1:  Ur the best. I do say. Why did you make this free? Its so high quality.

**Comment by BuilderGaming** [comment]
PS: The Gear is clear on the website but in gmod it gets really fuzzy,

![](http://i.gyazo.com/3c632929e7287a5bb2553c302ef83a5d.png)
![image](https://cloud.githubusercontent.com/assets/8619739/6241463/9b31cabc-b6eb-11e4-86a4-7a139111f011.png)

![](http://i.gyazo.com/6e70b82d45588f5e9e56a0a216735c84.png)

![](http://i.gyazo.com/6e70b82d45588f5e9e56a0a216735c84.png)

**Comment by BuilderGaming** [comment]
I fixed TTT thing now :P I THINK. But the Progress Bar and Gear need to be fixed. Can you change it to v1.0.9 so I know when its been updated :)

**Comment by iKlem** [comment]
- For the fuzzy gear, it's very strange, it append for me too but the image is a SVG so it can't be fuzzy.
I think i know where is the problem for the gear.
- For your question, i made this loading screen free, because i like to do web development and i don't want to sell it because we already have buy the game.
- For the fix, it will be an update, the v1.1, you can see with the "v1.1" branch, it will be updated a lot. And when it'll be finished, i'll do a merge with the "master" branch with a release.

**Comment by iKlem** [comment]
An update has been pushed, if you can do a feedback if the bugs/new things are correct on the gitter page of the project : https://gitter.im/iKlem/GoulpLoader
